import type { HunnyeoTip } from "./types";

// ── 제7장 발관리 ───────────────────────────────────────────────────────────
export const FOOT_TIPS: HunnyeoTip[] = [
  {
    id: "foot-bakingsoda",
    category: "foot",
    title: "베이킹소다 발각질 팩",
    materials: ["베이킹소다", "따뜻한 물", "부드러운 수건"],
    steps: [
      "따뜻한 물에 베이킹소다를 풀고 발을 10분 담가요.",
      "베이킹소다와 물을 1대 1로 개어 뒤꿈치에 발라요.",
      "10분 뒤 수건으로 살살 문질러 씻어내요.",
      "마무리로 보습 크림을 발라요.",
    ],
    effect: "묵은 각질이 정리되어 매끈한 발이 돼요.",
    caution: "매일 하면 자극이 될 수 있어요. 일주일에 한 번이면 충분해요.",
    tags: ["각질제거", "주 1회", "샌들시즌"],
    points: 10,
    type: "action",
  },
  {
    id: "foot-vinegar",
    category: "foot",
    title: "식초 족욕",
    materials: ["따뜻한 물 4", "식초 1"],
    steps: [
      "따뜻한 물과 식초를 4대 1로 섞어요.",
      "발을 10~15분 담가요.",
      "물기를 닦고 보습제를 발라 마무리해요.",
    ],
    effect: "각질이 부드러워지고 발 냄새가 줄어들어요.",
    caution: "상처가 있거나 무좀 치료 중이라면 자극이 될 수 있으니 피해 주세요.",
    tags: ["족욕", "냄새케어", "각질연화"],
    points: 10,
    type: "action",
  },
  {
    id: "foot-socks",
    category: "foot",
    title: "바세린 바르고 수면양말 신기",
    materials: ["바세린", "수면양말"],
    steps: [
      "씻은 뒤 발을 깨끗이 말려요.",
      "뒤꿈치 위주로 바세린을 도톰하게 발라요.",
      "수면양말을 신고 그대로 자요.",
    ],
    effect: "아침에 촉촉하고 부드러운 발로 일어날 수 있어요.",
    tags: ["자기전루틴", "보습", "겨울필수"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-file",
    category: "foot",
    title: "각질제거기 바르게 쓰기",
    materials: ["발 각질제거기"],
    steps: [
      "족욕으로 각질을 충분히 불려요.",
      "물기를 닦고 한 방향으로만 밀어요.",
      "한 번에 다 밀지 말고 조금씩 여러 번에 나눠요.",
      "끝나면 크림을 발라 마무리해요.",
    ],
    effect: "발바닥이 매끈해지고 갈라짐이 줄어들어요.",
    caution: "한 번에 두껍게 밀면 오히려 각질이 더 두껍게 올라옵니다.",
    tags: ["각질", "주 1회", "주의"],
    points: 10,
    type: "action",
  },
  {
    id: "foot-salt-bath",
    category: "foot",
    title: "굵은소금 족욕",
    materials: ["굵은소금 한 줌", "따뜻한 물"],
    steps: [
      "대야에 따뜻한 물을 받고 굵은소금을 풀어요.",
      "발을 15분 담그고 발가락을 쥐었다 폈다 해요.",
      "찬물로 헹구고 물기를 닦아요.",
    ],
    effect: "하루 종일 걸어 피로한 발이 개운해져요.",
    tags: ["족욕", "피로", "15분"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-toe-stretch",
    category: "foot",
    title: "발가락 벌리기",
    steps: [
      "손가락을 발가락 사이에 하나씩 끼워요.",
      "발목을 천천히 열 번 돌려요.",
      "반대쪽 발도 같은 방법으로 해요.",
    ],
    effect: "굽은 발가락이 펴지고 발 피로가 풀려요.",
    tags: ["발가락", "스트레칭", "자기전"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-tea-deodorize",
    category: "foot",
    title: "녹차 티백으로 신발 냄새 잡기",
    materials: ["쓰지 않은 녹차 티백 2개"],
    steps: [
      "신발을 하루 통풍이 되는 곳에 둬요.",
      "마른 녹차 티백을 신발 안에 하나씩 넣어요.",
      "다음 날 아침에 꺼내요.",
    ],
    effect: "신발에 밴 냄새가 옅어지고 습기도 함께 잡혀요.",
    tags: ["냄새", "녹차", "하룻밤"],
    points: 6,
    type: "action",
  },
  {
    id: "foot-shoe-rotate",
    category: "foot",
    title: "신발 번갈아 신기",
    steps: [
      "같은 신발을 이틀 연속 신지 말아요.",
      "벗은 신발은 통풍이 되는 곳에 하루 두어요.",
      "신문지를 뭉쳐 넣어 두면 습기가 빠져요.",
    ],
    effect: "신발 냄새와 발 냄새가 함께 줄어들어요.",
    tags: ["신발", "냄새", "습관"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-heel-height",
    category: "foot",
    title: "굽 높은 날과 낮은 날 나누기",
    steps: [
      "높은 굽은 이틀 연속 신지 말아요.",
      "가방에 접이식 신발을 하나 넣어 다녀요.",
      "굽 신은 날 밤에는 종아리를 꼭 늘려요.",
    ],
    effect: "발 앞쪽 통증과 종아리 뭉침이 줄어들어요.",
    tags: ["구두", "발앞꿈치", "습관"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-pumice-care",
    category: "foot",
    title: "발톱 일자로 자르기",
    materials: ["발톱깎이"],
    steps: [
      "목욕 후 발톱이 부드러울 때 잘라요.",
      "둥글게 파지 말고 일자로 잘라요.",
      "모서리는 줄로 살짝만 다듬어요.",
    ],
    effect: "발톱이 살을 파고드는 일을 막을 수 있어요.",
    tags: ["발톱", "내향성예방", "기본"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-massage-night",
    category: "foot",
    title: "발바닥 지압",
    materials: ["로션", "골프공 또는 병"],
    steps: [
      "발바닥에 로션을 바르고 엄지로 꾹꾹 눌러요.",
      "발바닥 가운데를 따라 뒤꿈치에서 발가락 쪽으로 밀어요.",
      "공을 발밑에 두고 굴려 주면 더 편해요.",
    ],
    effect: "다리가 가벼워지고 잠이 잘 와요.",
    tags: ["지압", "자기전", "3분"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-lemon-scrub",
    category: "foot",
    title: "레몬 발각질 문지르기",
    materials: ["레몬 1/2개"],
    steps: [
      "족욕으로 발을 충분히 불려요.",
      "레몬 단면으로 뒤꿈치를 살살 문질러요.",
      "물로 헹구고 보습 크림을 발라요.",
    ],
    effect: "레몬산이 각질을 부드럽게 녹여 매끈해져요.",
    caution: "상처가 있으면 따가울 수 있어요. 상처 부위는 피하세요.",
    tags: ["레몬", "각질", "족욕후"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-plastic-wrap",
    category: "foot",
    title: "랩 씌워 보습 밀착시키기",
    materials: ["바세린 또는 보습크림", "비닐랩"],
    steps: [
      "발에 보습크림을 두툼하게 발라요.",
      "비닐랩으로 감싸고 10분 정도 둬요.",
      "랩을 벗기고 남은 크림을 마사지하듯 흡수시켜요.",
    ],
    effect: "보습 성분이 더 깊이 스며들어 뒤꿈치가 촉촉해져요.",
    caution: "너무 오래 감싸두면 습해서 트러블이 날 수 있어요. 10분을 넘기지 마세요.",
    tags: ["랩보습", "뒤꿈치", "집중케어"],
    points: 8,
    type: "action",
  },
  {
    id: "foot-insole-change",
    category: "foot",
    title: "깔창 자주 바꾸기",
    materials: ["여분의 신발 깔창"],
    steps: [
      "자주 신는 신발의 깔창을 한 달에 한 번 정도 바꿔요.",
      "젖은 깔창은 그날 바로 말려요.",
    ],
    effect: "발 냄새와 무좀균이 자랄 환경을 줄일 수 있어요.",
    tags: ["깔창", "냄새예방", "위생"],
    points: 6,
    type: "action",
  },
];
