import type { HunnyeoTip } from "./types";

// ── 제1장 얼굴팩 ───────────────────────────────────────────────────────────
export const FACEPACK_TIPS: HunnyeoTip[] = [
  {
    id: "pack-apple",
    category: "facepack",
    title: "사과꿀 밀가루팩",
    materials: ["사과 1/4개", "꿀 1티스푼", "밀가루 2스푼"],
    steps: [
      "사과를 강판에 곱게 갈아요.",
      "간 사과에 꿀과 밀가루를 넣고 흘러내리지 않을 정도로 되직하게 섞어요.",
      "세안 후 물기를 닦고 눈과 입 주위를 피해 발라요.",
      "20분 뒤 미지근한 물로 씻어내고 마지막에 찬물로 헹궈요.",
    ],
    effect: "묵은 각질이 정리되어 뽀얀 피부를 얻을 수 있어요.",
    tags: ["미백", "각질정리", "주 2회"],
    points: 12,
    type: "action",
  },
  {
    id: "pack-orange",
    category: "facepack",
    title: "오렌지 밀가루팩",
    materials: ["오렌지 1/2개", "밀가루 2스푼", "꿀 약간"],
    steps: [
      "오렌지를 짜서 즙만 준비해요.",
      "오렌지즙에 밀가루와 꿀을 넣고 되직하게 섞어요.",
      "얼굴에 얇게 펴 바르고 20분 두었다가 씻어내요.",
    ],
    effect: "칙칙했던 얼굴빛이 화사해져요.",
    caution: "감귤류 즙을 바른 뒤 자외선을 받으면 색소침착이 생길 수 있어요. 저녁에 하고 다음 날은 자외선 차단제를 꼭 발라 주세요.",
    tags: ["비타민", "화사한 톤", "저녁에"],
    points: 12,
    type: "action",
  },
  {
    id: "pack-potato",
    category: "facepack",
    title: "감자팩",
    materials: ["감자 1개", "밀가루 1스푼"],
    steps: [
      "감자 껍질을 벗기고 강판에 곱게 갈아요.",
      "물기를 꼭 짜낸 뒤 밀가루를 섞어 되직하게 만들어요.",
      "얼굴과 눈 밑에 얇게 올리고 15분 뒤 씻어내요.",
    ],
    effect: "화끈거림이 가라앉고 부기가 빠져 편안한 피부가 돼요.",
    tags: ["진정", "부기완화", "눈밑"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-egg-white",
    category: "facepack",
    title: "계란 흰자팩",
    materials: ["계란 흰자 1개분", "밀가루 1스푼"],
    steps: [
      "계란 흰자를 거품이 살짝 날 때까지 저어요.",
      "밀가루를 넣어 농도를 맞춰요.",
      "코와 볼 위주로 얇게 바르고 10분 뒤 씻어내요.",
    ],
    effect: "피부결이 매끈해지고 모공이 조여진 느낌이 들어요.",
    tags: ["모공", "매끈한 결"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-cucumber",
    category: "facepack",
    title: "오이팩",
    materials: ["오이 1/3개", "밀가루 2작은술", "꿀 약간"],
    steps: [
      "오이를 강판에 곱게 갈아요.",
      "밀가루와 꿀을 넣어 흘러내리지 않게 섞어요.",
      "얼굴에 고르게 펴 바르고 15분 둬요.",
      "미지근한 물로 씻어내요.",
    ],
    effect: "달아오른 피부가 시원하게 가라앉고 수분이 채워져요. 얇게 썬 오이를 그대로 올려도 좋아요.",
    tags: ["수분", "진정", "여름"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-yogurt",
    category: "facepack",
    title: "요구르트팩",
    materials: ["무가당 플레인 요구르트 2스푼", "밀가루 1스푼"],
    steps: [
      "요구르트와 밀가루를 잘 섞어요.",
      "T존 위주로 도톰하게 발라요.",
      "15분 뒤 미지근한 물로 씻어내요.",
    ],
    effect: "번들거림이 줄어들고 피부가 보송해져요.",
    tags: ["지성피부", "피지관리"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-honey",
    category: "facepack",
    title: "꿀팩",
    materials: ["꿀 1스푼", "밀가루 1스푼"],
    steps: [
      "꿀과 밀가루를 1대 1로 섞어요.",
      "건조한 부위 위주로 얇게 발라요.",
      "15분 뒤 미지근한 물로 충분히 헹궈요.",
    ],
    effect: "당김이 사라지고 하루 종일 촉촉함이 유지돼요.",
    tags: ["건성피부", "보습", "겨울"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-greentea",
    category: "facepack",
    title: "녹차가루팩",
    materials: ["녹차가루 1티스푼", "밀가루 1스푼", "물 약간"],
    steps: [
      "녹차가루와 밀가루를 섞고 물을 조금씩 넣어 농도를 맞춰요.",
      "얼굴 전체에 얇게 발라요.",
      "15분 뒤 미지근한 물로 씻어내요.",
    ],
    effect: "번들거림이 잡히고 붉은 기가 차분해져요.",
    tags: ["진정", "붉은기", "피지"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-rice-water",
    category: "facepack",
    title: "쌀뜨물 세안",
    materials: ["쌀 두 번째 씻은 물"],
    steps: [
      "처음 씻은 물은 버리고 두 번째 쌀뜨물을 받아요.",
      "평소처럼 클렌저로 세안을 마쳐요.",
      "마지막 헹굼 단계에서 쌀뜨물로 얼굴을 여러 번 감싸듯 헹궈요.",
      "맑은 물로 한 번 더 가볍게 헹궈요.",
    ],
    effect: "피부결이 정돈되고 은은하게 맑아 보여요.",
    caution: "쌀뜨물은 상하기 쉬우니 받아 둔 당일에만 사용하세요.",
    tags: ["옛날방법", "세안", "피부결"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-rice-sediment",
    category: "facepack",
    title: "쌀뜨물 앙금팩",
    materials: ["쌀뜨물 한 컵", "밀가루 1스푼"],
    steps: [
      "쌀뜨물을 그릇에 받아 한나절 가라앉혀요.",
      "위쪽 맑은 물을 따라내고 아래 앙금만 남겨요.",
      "앙금에 밀가루를 섞어 얼굴에 바르고 15분 뒤 씻어내요.",
    ],
    effect: "각질이 부드럽게 정리되어 피부가 매끈해져요.",
    tags: ["옛날방법", "각질", "저렴한관리"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-lemon",
    category: "facepack",
    title: "레몬꿀 밀가루팩",
    materials: ["레몬즙 1티스푼", "꿀 1스푼", "밀가루 1스푼"],
    steps: [
      "세 가지 재료를 고루 섞어요.",
      "얼굴에 아주 얇게 바르고 10분만 둬요.",
      "미지근한 물로 깨끗이 씻어내요.",
    ],
    effect: "칙칙한 부분이 밝아 보여요.",
    caution: "레몬즙은 산성이 강해 자극이 될 수 있어요. 상처가 있거나 예민한 피부는 피하고, 팔 안쪽에서 먼저 시험해 보세요.",
    tags: ["미백", "10분", "민감성 주의"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-aloe",
    category: "facepack",
    title: "알로에 진정팩",
    materials: ["알로에 젤 2스푼"],
    steps: [
      "세안 후 물기를 가볍게 닦아요.",
      "알로에 젤을 도톰하게 올려요.",
      "15분 뒤 남은 젤을 닦아내거나 그대로 흡수시켜요.",
    ],
    effect: "햇볕에 그을려 화끈거리는 피부가 시원하게 가라앉아요.",
    tags: ["진정", "여름", "자외선 후"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-milk-cotton",
    category: "facepack",
    title: "우유 화장솜팩",
    materials: ["우유 반 컵", "화장솜 5장"],
    steps: [
      "화장솜을 차가운 우유에 충분히 적셔요.",
      "이마·볼·코·턱에 나누어 올려요.",
      "10분 뒤 떼어내고 물로 가볍게 헹궈요.",
    ],
    effect: "피부가 진정되고 촉촉하게 정돈돼요.",
    caution: "우유가 남으면 트러블의 원인이 될 수 있으니 반드시 물로 헹궈 주세요.",
    tags: ["진정", "간단", "10분"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-tomato",
    category: "facepack",
    title: "토마토팩",
    materials: ["토마토 1개", "우유 2스푼", "밀가루 2큰술"],
    steps: [
      "토마토 꼭지를 떼고 믹서에 갈아요.",
      "간 토마토에 우유와 밀가루를 넣어 되직하게 섞어요.",
      "얼굴에 펴 바르고 15분 둬요.",
      "미지근한 물로 깨끗이 씻어내요.",
    ],
    effect: "붉은 기가 가라앉고 피부가 한 톤 맑아 보여요.",
    tags: ["미백", "진정", "15분"],
    points: 12,
    type: "action",
  },
  {
    id: "pack-oatmeal",
    category: "facepack",
    title: "오트밀팩",
    materials: ["오트밀 2큰술", "우유 또는 요구르트 적당량"],
    steps: [
      "오트밀을 곱게 부숴요.",
      "우유를 조금씩 부어 걸쭉하게 만들어요.",
      "얼굴에 도톰하게 올리고 15분 둬요.",
      "손끝으로 살살 굴리며 씻어내요.",
    ],
    effect: "묵은 각질이 부드럽게 정리되고 피부결이 매끈해져요.",
    tags: ["각질", "저자극", "15분"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-banana",
    category: "facepack",
    title: "바나나팩",
    materials: ["잘 익은 바나나 1/2개", "꿀 1티스푼", "밀가루 1스푼"],
    steps: [
      "바나나를 포크로 곱게 으깨요.",
      "꿀과 밀가루를 넣어 섞어요.",
      "얼굴에 바르고 15분 두었다가 씻어내요.",
    ],
    effect: "당김이 사라지고 피부가 부드럽게 가라앉아요.",
    tags: ["건성", "보습", "겨울"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-strawberry",
    category: "facepack",
    title: "딸기 요구르트팩",
    materials: ["딸기 3~4개", "무가당 요구르트 2스푼", "밀가루 1스푼"],
    steps: [
      "딸기를 으깨어 요구르트와 섞어요.",
      "밀가루로 농도를 맞춰요.",
      "얼굴에 얇게 바르고 10분 둬요.",
      "미지근한 물로 충분히 헹궈요.",
    ],
    effect: "피부가 산뜻해지고 얼굴빛이 화사해져요.",
    caution: "딸기의 산 성분이 자극이 될 수 있으니 10분을 넘기지 말고, 예민한 피부는 피해 주세요.",
    tags: ["화사한 톤", "10분", "제철"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-type-guide",
    category: "facepack",
    title: "피부 타입별 팩 조합표",
    steps: [
      "농도는 밀가루로 맞추는 것이 기본이에요.",
      "건성 피부는 꿀 한 스푼을 넣어요.",
      "지성 피부는 무가당 요구르트를 넣어요.",
      "탄력이 고민이면 계란 노른자를 넣어요.",
      "민감성 피부는 다른 재료 없이 생수로만 개어요.",
    ],
    effect: "내 피부에 맞는 조합을 찾으면 자극 없이 관리할 수 있어요.",
    tags: ["조합표", "기본공식", "저장용"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-carrot",
    category: "facepack",
    title: "당근팩",
    materials: ["당근 1/2개", "밀가루 1스푼", "꿀 약간"],
    steps: [
      "당근을 강판에 곱게 갈아요.",
      "즙을 살짝 짜내고 밀가루와 꿀을 넣어 되직하게 섞어요.",
      "얼굴에 펴 바르고 15분 뒤 씻어내요.",
    ],
    effect: "칙칙한 피부에 생기가 돌고 잡티가 옅어져 보여요.",
    tags: ["미백", "비타민", "15분"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-kiwi",
    category: "facepack",
    title: "키위팩",
    materials: ["키위 1/2개", "무가당 요구르트 1스푼", "밀가루 1스푼"],
    steps: [
      "키위를 곱게 으깨요.",
      "요구르트와 밀가루를 넣어 섞어요.",
      "T존 위주로 바르고 10분 뒤 씻어내요.",
    ],
    effect: "각질이 정리되고 피부가 화사해 보여요.",
    caution: "키위의 산 성분이 자극이 될 수 있어요. 10분을 넘기지 마세요.",
    tags: ["각질", "10분", "화사한톤"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-grape",
    category: "facepack",
    title: "포도팩",
    materials: ["포도 5알", "밀가루 1스푼"],
    steps: [
      "포도를 껍질째 곱게 으깨요.",
      "밀가루를 넣어 되직하게 섞어요.",
      "얼굴에 바르고 15분 뒤 씻어내요.",
    ],
    effect: "피부에 은은한 윤기가 돌아요.",
    tags: ["윤기", "15분"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-peach",
    category: "facepack",
    title: "복숭아팩",
    materials: ["복숭아 1/2개", "밀가루 1스푼"],
    steps: [
      "복숭아 껍질을 벗기고 곱게 으깨요.",
      "밀가루를 섞어 농도를 맞춰요.",
      "얼굴에 바르고 15분 뒤 씻어내요.",
    ],
    effect: "피부가 부드러워지고 은은한 향이 남아요.",
    caution: "복숭아 털 성분에 예민하면 자극이 될 수 있어요. 팔 안쪽에 먼저 시험해 보세요.",
    tags: ["보습", "제철", "15분"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-soybean",
    category: "facepack",
    title: "콩가루팩",
    materials: ["노란콩가루 2스푼", "물 또는 우유 약간"],
    steps: [
      "콩가루에 물을 조금씩 넣어 되직하게 개어요.",
      "얼굴 전체에 바르고 15분 뒤 씻어내요.",
    ],
    effect: "피부가 매끈해지고 한 톤 화사해지는 느낌이 들어요.",
    tags: ["매끈함", "전통재료"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-mungbean",
    category: "facepack",
    title: "녹두가루팩",
    materials: ["녹두가루 2스푼", "물 약간"],
    steps: [
      "녹두가루에 물을 부어 되직하게 개어요.",
      "좁쌀 트러블이 많은 부위 위주로 발라요.",
      "15분 뒤 씻어내요.",
    ],
    effect: "좁쌀 트러블이 가라앉고 피지가 조절돼요.",
    tags: ["트러블", "피지조절", "전통재료"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-sesame-oil",
    category: "facepack",
    title: "참기름 마사지",
    materials: ["참기름 몇 방울"],
    steps: [
      "세안 후 물기 남은 얼굴에 참기름을 소량 덜어요.",
      "손끝으로 부드럽게 마사지해요.",
      "따뜻한 물수건으로 닦아내요.",
    ],
    effect: "피부가 매끈해지고 각질이 부드럽게 정리돼요.",
    caution: "지성 피부는 소량만 쓰고, 트러블 부위는 피하세요.",
    tags: ["마사지", "저녁관리"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-olive-oil",
    category: "facepack",
    title: "올리브오일 클렌징",
    materials: ["올리브오일 1스푼", "화장솜"],
    steps: [
      "화장솜에 올리브오일을 적셔요.",
      "얼굴을 원을 그리며 부드럽게 닦아내요.",
      "미지근한 물로 헹궈요.",
    ],
    effect: "묵은 메이크업 잔여물과 노폐물이 깨끗이 지워져요.",
    tags: ["클렌징", "보습", "저녁"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-blacksesame",
    category: "facepack",
    title: "흑임자팩",
    materials: ["흑임자가루 1스푼", "꿀 1스푼"],
    steps: [
      "흑임자가루와 꿀을 섞어요.",
      "얼굴에 얇게 펴 바르고 15분 뒤 씻어내요.",
    ],
    effect: "피부에 윤기가 돌고 탄력이 살아나는 느낌이 들어요.",
    tags: ["윤기", "탄력", "전통재료"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-seaweed",
    category: "facepack",
    title: "미역팩",
    materials: ["마른미역 1장", "물 약간"],
    steps: [
      "미역을 물에 불려 부드럽게 만들어요.",
      "얼굴 크기로 잘라 붙여요.",
      "15분 뒤 떼어내고 남은 점액은 흡수시켜요.",
    ],
    effect: "미네랄이 흡수되어 피부에 탄력과 촉촉함을 더해줘요.",
    tags: ["탄력", "미네랄", "특이템"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-jujube",
    category: "facepack",
    title: "대추팩",
    materials: ["말린 대추 3알", "물", "밀가루 1스푼"],
    steps: [
      "대추를 물에 푹 삶아 부드럽게 만들어요.",
      "씨를 빼고 곱게 으깨요.",
      "밀가루를 섞어 얼굴에 바르고 15분 둬요.",
    ],
    effect: "혈색이 좋아지고 생기 있는 얼굴빛이 돼요.",
    tags: ["혈색", "생기", "전통재료"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-brownsugar-scrub",
    category: "facepack",
    title: "흑설탕 스크럽",
    materials: ["흑설탕 1스푼", "올리브오일 1스푼"],
    steps: [
      "흑설탕과 오일을 섞어요.",
      "입술과 코 주위처럼 각질 많은 부위를 살살 문질러요.",
      "물로 헹궈요.",
    ],
    effect: "거친 각질이 부드럽게 벗겨져 매끈해져요.",
    caution: "세게 문지르면 자극될 수 있어요. 살살 문지르세요.",
    tags: ["스크럽", "각질", "부분관리"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-vinegar-flour",
    category: "facepack",
    title: "식초 밀가루팩",
    materials: ["식초 1티스푼", "밀가루 2스푼", "물 약간"],
    steps: [
      "식초와 밀가루, 물을 섞어 농도를 맞춰요.",
      "피지 많은 부위 위주로 바르고 10분 둬요.",
      "씻어내요.",
    ],
    effect: "피지와 각질이 정리되고 피부 톤이 정돈돼요.",
    caution: "식초 향이 강하니 환기가 잘 되는 곳에서 하고, 상처 부위는 피하세요.",
    tags: ["피지관리", "10분"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-salt-scrub",
    category: "facepack",
    title: "소금 스크럽",
    materials: ["고운 소금 1스푼", "물 약간"],
    steps: [
      "소금에 물을 살짝 섞어 알갱이가 남게 만들어요.",
      "코와 이마 위주로 부드럽게 문질러요.",
      "물로 헹궈요.",
    ],
    effect: "블랙헤드와 각질이 정리돼요.",
    caution: "상처나 트러블 부위에는 사용하지 마세요.",
    tags: ["블랙헤드", "각질", "T존"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-apricot",
    category: "facepack",
    title: "살구팩",
    materials: ["잘 익은 살구 1개", "밀가루 1스푼"],
    steps: [
      "살구 껍질을 벗기고 으깨요.",
      "밀가루를 섞어 되직하게 만들어요.",
      "얼굴에 바르고 15분 뒤 씻어내요.",
    ],
    effect: "피부가 촉촉해지고 은은한 윤기가 돌아요.",
    tags: ["보습", "윤기", "제철"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-grapefruit",
    category: "facepack",
    title: "자몽팩",
    materials: ["자몽즙 1티스푼", "꿀 1스푼", "밀가루 1스푼"],
    steps: [
      "세 가지 재료를 섞어요.",
      "얼굴에 얇게 바르고 10분 둬요.",
      "미지근한 물로 씻어내요.",
    ],
    effect: "칙칙함이 걷히고 상큼하게 화사해져요.",
    caution: "감귤류 성분이 자극이 될 수 있어요. 자외선 차단을 꼭 해주세요.",
    tags: ["미백", "자외선주의"],
    points: 8,
    type: "action",
  },
  {
    id: "pack-melon",
    category: "facepack",
    title: "멜론팩",
    materials: ["멜론 과육 2스푼", "밀가루 1스푼"],
    steps: [
      "멜론 과육을 곱게 으깨요.",
      "밀가루를 섞어 되직하게 만들어요.",
      "얼굴에 펴 바르고 15분 둬요.",
    ],
    effect: "피부에 수분이 채워지고 진정 효과를 느낄 수 있어요.",
    tags: ["수분", "진정", "여름"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-yulpi",
    category: "facepack",
    title: "율피(밤 속껍질)팩",
    materials: ["율피 가루 1스푼", "꿀 1스푼", "우유 약간"],
    steps: [
      "율피 가루에 꿀과 우유를 넣어 되직하게 개어요.",
      "얼굴에 얇게 펴 바르고 15분 둬요.",
      "미지근한 물로 씻어내요.",
    ],
    effect: "율피에 든 타닌 성분이 모공을 조여 주고 잡티를 옅게 해줘요. 동의보감에도 주름에 좋다고 실려 있는 재료예요.",
    tags: ["율피", "모공", "전통재료"],
    points: 10,
    type: "action",
  },
  {
    id: "pack-licorice",
    category: "facepack",
    title: "감초가루 진정팩",
    materials: ["감초가루 1스푼", "물 또는 꿀 약간"],
    steps: [
      "감초가루에 물이나 꿀을 넣어 되직하게 개어요.",
      "붉은 기가 있는 부위 위주로 얇게 발라요.",
      "15분 뒤 미지근한 물로 씻어내요.",
    ],
    effect: "항염 성분이 있어 붉은 기와 예민함을 가라앉히는 데 도움을 줘요.",
    tags: ["감초", "진정", "민감성"],
    points: 8,
    type: "action",
  },
];
