import type { HunnyeoTip } from "./types";

// ── 제12장 생활습관 ────────────────────────────────────────────────────────
export const LIFE_TIPS: HunnyeoTip[] = [
  {
    id: "life-sleep-time",
    category: "life",
    title: "열 시에서 두 시 사이에 자기",
    steps: [
      "밤 열 시에서 새벽 두 시 사이에는 잠들어 있게 해요.",
      "자기 한 시간 전에는 방 불을 어둡게 해요.",
      "주말에도 일어나는 시간을 비슷하게 맞춰요.",
    ],
    effect: "피부와 머리카락이 회복되고 다음 날 얼굴빛이 달라져요.",
    tags: ["수면", "피부회복", "기본중의기본"],
    points: 12,
    type: "action",
  },
  {
    id: "life-humidifier",
    category: "life",
    title: "젖은 수건 걸어 두기",
    materials: ["수건 1~2장"],
    steps: [
      "잠들기 전 젖은 수건을 짜서 방에 걸어요.",
      "난방을 켠 날에는 두 장 걸어요.",
    ],
    effect: "아침에 목이 마르지 않고 피부 당김도 줄어들어요.",
    tags: ["습도", "겨울", "간단"],
    points: 8,
    type: "action",
  },
  {
    id: "life-perfume",
    category: "life",
    title: "향수 은은하게 뿌리기",
    materials: ["향수"],
    steps: [
      "옷을 입기 전 몸에서 20cm 떨어뜨려 공중에 뿌리고 그 아래를 지나가요.",
      "손목·귀 뒤·머리끝 중 한 곳만 골라요.",
      "손목끼리 비비지 말아요.",
    ],
    effect: "가까이 왔을 때만 은은하게 느껴지는 향이 만들어져요.",
    tags: ["향수", "20cm", "은은하게"],
    points: 8,
    type: "action",
  },
  {
    id: "life-hair-scent",
    category: "life",
    title: "머리에서 좋은 냄새 나게 하기",
    materials: ["빗", "향수"],
    steps: [
      "빗에 향수를 한 번 뿌려요.",
      "3초 기다렸다가 머리를 빗어요.",
    ],
    effect: "머리카락이 흔들릴 때마다 은은한 향이 남아요.",
    caution: "머리카락에 직접 뿌리면 알코올 때문에 건조해질 수 있어요.",
    tags: ["머리향", "빗", "요령"],
    points: 8,
    type: "action",
  },
  {
    id: "life-closet-scent",
    category: "life",
    title: "옷장에 향 넣어 두기",
    materials: ["섬유유연제 묻힌 천 조각 또는 비누 한 개"],
    steps: [
      "쓰지 않는 비누를 포장한 채로 옷장에 넣어요.",
      "서랍마다 하나씩 넣어요.",
      "한 달에 한 번 위치를 바꿔요.",
    ],
    effect: "꺼내 입는 옷에서 은은한 향이 나요.",
    tags: ["옷장", "비누", "한달"],
    points: 6,
    type: "action",
  },
  {
    id: "life-morning-light",
    category: "life",
    title: "아침에 커튼 걷기",
    steps: [
      "일어나면 바로 커튼을 걷고 창가에 서요.",
      "5분 정도 바깥 빛을 봐요.",
    ],
    effect: "잠이 빨리 깨고 밤에 잠드는 시간도 앞당겨져요.",
    tags: ["아침", "5분", "수면리듬"],
    points: 8,
    type: "action",
  },
  {
    id: "life-phone-off",
    category: "life",
    title: "자기 전 화면 끄기",
    steps: [
      "잠들기 30분 전에 휴대전화를 손이 닿지 않는 곳에 둬요.",
      "대신 책이나 라디오를 켜요.",
    ],
    effect: "잠들기까지 걸리는 시간이 짧아지고 다음 날 눈이 덜 붓어요.",
    tags: ["수면", "30분", "습관"],
    points: 10,
    type: "action",
  },
  {
    id: "life-towel-change",
    category: "life",
    title: "세수 수건 따로 쓰기",
    materials: ["작은 수건 여러 장"],
    steps: [
      "얼굴 전용 수건을 따로 정해요.",
      "이틀에 한 번은 새 수건으로 바꿔요.",
      "얼굴은 문지르지 말고 눌러서 닦아요.",
    ],
    effect: "트러블이 줄고 세안 후 자극이 덜해요.",
    tags: ["수건", "트러블예방", "습관"],
    points: 8,
    type: "action",
  },
  {
    id: "life-salt-gargle",
    category: "life",
    title: "소금물 가글",
    materials: ["따뜻한 물 한 컵", "소금 반 티스푼"],
    steps: [
      "따뜻한 물에 소금을 녹여요.",
      "한 모금 머금고 목 뒤쪽까지 닿도록 10초 가글해요.",
      "뱉어내고 두세 번 반복해요.",
    ],
    effect: "목이 칼칼할 때 개운해지고 입안이 산뜻해져요.",
    caution: "삼키지 말고 뱉어 주세요. 너무 짜게 타면 오히려 점막이 자극돼요.",
    tags: ["환절기", "10초", "옛날방법"],
    points: 8,
    type: "action",
  },
  {
    id: "life-lotion-3min",
    category: "life",
    title: "씻고 3분 안에 바르기",
    materials: ["바디로션"],
    steps: [
      "샤워를 마치고 수건으로 물기를 톡톡 닦아요.",
      "물기가 살짝 남아 있을 때 바로 로션을 발라요.",
      "팔꿈치·무릎·발뒤꿈치처럼 거친 곳을 먼저 발라요.",
    ],
    effect: "수분이 날아가기 전에 잡아 두어 하루 종일 촉촉해요.",
    tags: ["보습", "3분", "샤워후"],
    points: 8,
    type: "action",
  },
  {
    id: "life-tv-stretch",
    category: "life",
    title: "텔레비전 보면서 스트레칭",
    steps: [
      "광고가 나오면 일어나 목과 어깨를 돌려요.",
      "바닥에 앉아 다리를 벌리고 상체를 앞으로 숙여요.",
      "누워서 무릎을 안고 좌우로 흔들어요.",
    ],
    effect: "따로 시간을 내지 않아도 몸이 굳지 않고 자세가 유지돼요.",
    tags: ["광고시간", "스트레칭", "생활습관"],
    points: 8,
    type: "action",
  },
  {
    id: "life-brush-clean",
    category: "life",
    title: "화장 도구 씻기",
    materials: ["중성 세제 또는 비누", "미온수"],
    steps: [
      "퍼프와 브러시를 미온수에 담가요.",
      "세제를 조금 풀어 조물조물 빨아요.",
      "충분히 헹구고 눕혀서 그늘에 말려요.",
      "퍼프는 주 1회, 브러시는 2주에 한 번 씻어요.",
    ],
    effect: "화장이 잘 먹고 트러블이 눈에 띄게 줄어들어요.",
    tags: ["퍼프", "브러시", "주 1회"],
    points: 10,
    type: "action",
  },
  {
    id: "life-bag-light",
    category: "life",
    title: "가방 가볍게 하고 양쪽 번갈아 메기",
    steps: [
      "가방에서 오늘 쓰지 않을 물건을 빼요.",
      "한쪽 어깨로만 메지 말고 번갈아 메요.",
      "무거운 날은 배낭이나 크로스백을 써요.",
    ],
    effect: "어깨가 한쪽으로 기울지 않아 자세가 반듯해져요.",
    tags: ["가방", "어깨", "습관"],
    points: 8,
    type: "action",
  },
  {
    id: "life-water-bottle",
    category: "life",
    title: "물병 들고 다니기",
    materials: ["텀블러 또는 물병"],
    steps: [
      "아침에 물병을 채워 가방에 넣어요.",
      "점심 전까지 절반을 비우는 것을 목표로 해요.",
      "다 마시면 한 번 더 채워요.",
    ],
    effect: "하루 물 양이 자연스럽게 늘어 피부와 컨디션이 좋아져요.",
    tags: ["수분", "텀블러", "매일"],
    points: 8,
    type: "action",
  },
  {
    id: "life-sunscreen-habit",
    category: "life",
    title: "현관에 자외선 차단제 두기",
    materials: ["자외선 차단제"],
    steps: [
      "신발장 위에 자외선 차단제를 놓아요.",
      "신발을 신기 전에 바르는 것으로 순서를 정해요.",
      "흐린 날에도 똑같이 발라요.",
    ],
    effect: "잊지 않고 매일 바르게 되어 잡티가 늦게 생겨요.",
    tags: ["자외선", "현관", "매일"],
    points: 10,
    type: "action",
  },
  {
    id: "life-diary",
    category: "life",
    title: "다이어리 꾸미기",
    materials: ["다이어리", "스티커", "색펜"],
    steps: [
      "하루에 한 줄만 적는다고 정해요.",
      "좋았던 일 하나와 내일 할 일 하나만 써요.",
      "스티커는 다 쓴 날에만 붙여요.",
    ],
    effect: "기분이 정리되고 예전 다이어리 감성도 되살아나요.",
    tags: ["다이어리", "한줄", "추억"],
    points: 6,
    type: "action",
  },
  {
    id: "life-mirror-check",
    category: "life",
    title: "나가기 전 전신거울 3초 확인",
    materials: ["전신거울"],
    steps: [
      "현관에서 전신거울을 3초만 봐요.",
      "어깨가 펴졌는지, 옷매무새가 맞는지 확인해요.",
    ],
    effect: "작은 흐트러짐을 잡아 하루 인상이 달라져요.",
    tags: ["거울", "3초", "습관"],
    points: 6,
    type: "action",
  },
  {
    id: "life-plant-room",
    category: "life",
    title: "방에 화분 하나 두기",
    materials: ["작은 화분"],
    steps: [
      "햇빛이 드는 창가에 화분을 하나 둬요.",
      "물 주는 요일을 정해 잊지 않고 챙겨요.",
    ],
    effect: "방 공기가 조금 더 쾌적해지고 마음도 차분해져요.",
    tags: ["화분", "방꾸미기", "습관"],
    points: 6,
    type: "action",
  },
  {
    id: "life-posture-alarm",
    category: "life",
    title: "자세 알림 맞춰 두기",
    steps: [
      "한 시간마다 울리는 알람을 맞춰요.",
      "알람이 울리면 허리를 펴고 어깨를 활짝 열어요.",
    ],
    effect: "앉아 있는 동안 자세가 무너지는 걸 자주 알아차릴 수 있어요.",
    tags: ["자세", "알람", "습관"],
    points: 6,
    type: "action",
  },
  {
    id: "life-gratitude-note",
    category: "life",
    title: "자기 전 감사한 일 한 줄 쓰기",
    materials: ["다이어리나 메모장"],
    steps: [
      "자기 전 오늘 있었던 좋은 일 한 가지를 적어요.",
      "짧아도 괜찮아요. 한 줄이면 충분해요.",
    ],
    effect: "마음이 편안해지고 잠도 더 잘 오는 느낌을 줘요.",
    tags: ["감사일기", "한줄", "자기전"],
    points: 6,
    type: "action",
  },
  {
    id: "life-desk-tidy",
    category: "life",
    title: "자기 전 책상 정리",
    steps: [
      "자기 전 책상 위 물건을 제자리에 둬요.",
      "다음 날 쓸 물건만 눈에 보이게 남겨요.",
    ],
    effect: "아침에 어수선하지 않고 개운하게 하루를 시작할 수 있어요.",
    tags: ["정리정돈", "자기전", "습관"],
    points: 6,
    type: "action",
  },
  {
    id: "life-phone-off-hour",
    category: "life",
    title: "자기 한 시간 전 핸드폰 멀리하기",
    steps: [
      "자기 한 시간 전에는 핸드폰을 다른 방이나 손 닿지 않는 곳에 둬요.",
      "그 시간엔 책을 읽거나 스트레칭을 해요.",
    ],
    effect: "화면 빛 때문에 잠들기 어려운 걸 줄이고 피부 휴식 시간도 늘어나요.",
    tags: ["핸드폰", "수면", "습관"],
    points: 8,
    type: "action",
  },
  {
    id: "life-sunday-reset",
    category: "life",
    title: "일요일 저녁 한 주 준비",
    steps: [
      "다음 주 입을 옷을 미리 정해 둬요.",
      "화장품과 가방 속을 한 번 정리해요.",
      "다음 날 아침 할 일을 짧게 적어 둬요.",
    ],
    effect: "월요일 아침이 덜 정신없고 여유로워져요.",
    tags: ["일요일", "주간준비", "습관"],
    points: 8,
    type: "action",
  },
];
