import type { HunnyeoTip } from "./types";

// ── 제6장 두피·머리숱 ──────────────────────────────────────────────────────
export const SCALP_TIPS: HunnyeoTip[] = [
  {
    id: "scalp-massage",
    category: "scalp",
    title: "손끝 두피 마사지",
    steps: [
      "손톱이 아닌 손가락 끝 지문으로 두피를 짚어요.",
      "머리 앞쪽에서 정수리 방향으로 원을 그리며 눌러요.",
      "옆머리와 뒷목까지 골고루 3분 정도 해요.",
    ],
    effect: "두피가 시원해지고 머리카락에 영양이 잘 전달돼요.",
    tags: ["두피혈행", "3분", "매일"],
    points: 10,
    type: "action",
  },
  {
    id: "scalp-brush-massage",
    category: "scalp",
    title: "쿠션 브러시로 두드리기",
    materials: ["쿠션 브러시"],
    steps: [
      "브러시 등으로 두피를 가볍게 통통 두드려요.",
      "앞머리에서 뒤통수 방향으로 옮겨 가며 1분 정도 해요.",
    ],
    effect: "두피가 부드러워지고 머리를 감을 때 개운해요.",
    caution: "끝이 뾰족한 빗으로 두드리면 두피에 상처가 날 수 있어요.",
    tags: ["브러시", "1분", "간단"],
    points: 8,
    type: "action",
  },
  {
    id: "scalp-shampoo-way",
    category: "scalp",
    title: "샴푸 거품 내서 감기",
    steps: [
      "머리를 먼저 미온수로 1분 이상 충분히 적셔요.",
      "샴푸는 손에서 거품을 낸 뒤 두피에 올려요.",
      "손끝으로 두피를 문질러 감고 머리카락은 흐르는 거품으로 씻어요.",
      "샴푸가 남지 않도록 두 배 오래 헹궈요.",
    ],
    effect: "두피가 깨끗해지고 가려움과 냄새가 줄어들어요.",
    tags: ["기본", "두피세정", "매일"],
    points: 10,
    type: "action",
  },
  {
    id: "scalp-rinse-tip",
    category: "scalp",
    title: "린스는 두피에 닿지 않게",
    steps: [
      "린스는 귀 아래 길이부터 머리 끝에만 발라요.",
      "1분 정도 두었다가 충분히 헹궈요.",
    ],
    effect: "두피 트러블 없이 머리 끝만 부드러워져요.",
    tags: ["린스", "두피트러블", "기본"],
    points: 8,
    type: "action",
  },
  {
    id: "scalp-dandruff",
    category: "scalp",
    title: "비듬 줄이는 습관",
    steps: [
      "너무 뜨거운 물 대신 미온수로 감아요.",
      "샴푸를 두피에 남기지 않도록 충분히 헹궈요.",
      "머리는 반드시 말리고 자요.",
      "이 상태로 2주 이상 지켜보고 나아지지 않으면 진료를 받아요.",
    ],
    effect: "가려움과 하얀 각질이 눈에 띄게 줄어들어요.",
    caution: "비듬이 심하거나 붉은 발진이 함께 있으면 지루성 두피염일 수 있어요. 병원 진료를 받아 보세요.",
    tags: ["비듬", "2주", "습관"],
    points: 10,
    type: "action",
  },
  {
    id: "scalp-hair-grow",
    category: "scalp",
    title: "머리 빨리 기르는 생활습관",
    steps: [
      "달걀·콩·생선 같은 단백질을 끼니마다 챙겨요.",
      "밤 열 시에서 새벽 두 시 사이에는 잠들어 있게 해요.",
      "갈라진 끝은 두 달에 한 번 다듬어요.",
      "머리를 꽉 묶는 습관을 줄여요.",
    ],
    effect: "머리카락이 덜 끊어져 기르는 속도가 눈에 띄게 빨라져요.",
    tags: ["단백질", "수면", "기르기"],
    points: 12,
    type: "action",
  },
  {
    id: "scalp-loose-tie",
    category: "scalp",
    title: "느슨하게 묶기",
    materials: ["곱창밴드 또는 부드러운 머리끈"],
    steps: [
      "고무줄 대신 천으로 감싼 머리끈을 써요.",
      "묶는 위치를 매일 조금씩 바꿔요.",
      "집에서는 풀고 지내요.",
    ],
    effect: "이마와 정수리 쪽 머리카락이 덜 빠져요.",
    tags: ["견인탈모예방", "머리끈", "습관"],
    points: 10,
    type: "action",
  },
  {
    id: "scalp-hat",
    category: "scalp",
    title: "햇볕 강한 날 모자 쓰기",
    materials: ["모자 또는 양산"],
    steps: [
      "한여름 낮에는 모자나 양산을 챙겨요.",
      "땀이 찬 모자는 그날 바로 말려요.",
    ],
    effect: "두피가 타지 않고 머리카락도 덜 상해요.",
    tags: ["자외선", "여름", "두피보호"],
    points: 8,
    type: "action",
  },
  {
    id: "scalp-green-tea-rinse",
    category: "scalp",
    title: "녹차물 두피 헹굼",
    materials: ["녹차 티백 2개", "따뜻한 물 한 대야"],
    steps: [
      "티백을 우려 미지근하게 식혀요.",
      "샴푸 후 이 물로 두피를 적셔 1분 두었다가 헹궈요.",
    ],
    effect: "두피 냄새가 줄고 개운한 느낌이 오래가요.",
    tags: ["녹차", "두피냄새", "주 1회"],
    points: 8,
    type: "action",
  },
  {
    id: "scalp-stress",
    category: "scalp",
    title: "머리 감을 때 힘 빼기",
    steps: [
      "손톱을 세워 긁지 말고 지문으로만 문질러요.",
      "머리를 감을 때 숨을 참지 말고 천천히 쉬어요.",
      "따뜻한 물로 목덜미를 3초 정도 데워요.",
    ],
    effect: "두피 상처가 줄고 머리 감는 시간이 편안해져요.",
    tags: ["기본", "두피보호", "매일"],
    points: 8,
    type: "action",
  },
];
