import type { HunnyeoTip } from "./types";

// ── 제9장 입술·치아 ────────────────────────────────────────────────────────
export const LIP_TIPS: HunnyeoTip[] = [
  {
    id: "lip-honey-sleep",
    category: "lip",
    title: "꿀 얹고 자기",
    materials: ["꿀 조금", "랩 조각"],
    steps: [
      "자기 전 입술을 미온수로 닦아 주세요.",
      "꿀을 입술 위에 도톰하게 올려 주세요.",
      "랩을 입술 크기로 잘라 덮어 주세요.",
      "10분 뒤 랩을 떼고 남은 꿀을 닦아낸 뒤 그대로 주무세요.",
    ],
    effect: "각질이 부드럽게 불어 다음 날 입술이 매끈해져요.",
    tags: ["꿀", "자기전", "10분"],
    points: 12,
    type: "action",
  },
  {
    id: "lip-honey-sugar",
    category: "lip",
    title: "꿀설탕 입술 스크럽",
    materials: ["꿀 1티스푼", "설탕 1/2티스푼"],
    steps: [
      "꿀과 설탕을 섞어 주세요.",
      "입술에 올리고 손끝으로 아주 살살 굴려 주세요.",
      "30초 뒤 미온수로 닦아내 주세요.",
      "바로 립밤을 발라 주세요.",
    ],
    effect: "일어난 각질이 정리되어 입술색이 또렷해져요.",
    caution: "세게 문지르면 상처가 나요. 주 1회, 30초를 넘기지 마세요.",
    tags: ["스크럽", "주 1회", "30초"],
    points: 10,
    type: "action",
  },
  {
    id: "lip-vaseline-pack",
    category: "lip",
    title: "바세린 입술팩",
    materials: ["바세린", "랩 조각"],
    steps: [
      "입술에 바세린을 두껍게 발라 주세요.",
      "랩을 덮고 5분 두세요.",
      "면봉으로 각질을 부드럽게 밀어내 주세요.",
    ],
    effect: "묵은 각질이 힘들이지 않고 정리돼요.",
    tags: ["바세린", "5분", "각질"],
    points: 10,
    type: "action",
  },
  {
    id: "lip-no-lick",
    category: "lip",
    title: "입술 핥지 않기",
    steps: [
      "입술이 마르면 핥는 대신 립밤을 발라 주세요.",
      "가방과 책상에 립밤을 하나씩 두세요.",
      "입술을 뜯는 습관이 있다면 손을 다른 데 두는 연습을 해 주세요.",
    ],
    effect: "갈라짐과 각질이 되풀이되는 고리를 끊을 수 있어요.",
    tags: ["습관", "기본", "매일"],
    points: 10,
    type: "action",
  },
  {
    id: "lip-tint-base",
    category: "lip",
    title: "틴트 바르기 전 밑작업",
    materials: ["립밤", "면봉"],
    steps: [
      "립밤을 바르고 5분 기다려 주세요.",
      "면봉으로 남은 기름기를 살짝 눌러 닦아 주세요.",
      "그 위에 틴트를 안쪽부터 발라 주세요.",
    ],
    effect: "틴트가 각질 사이에 끼지 않고 고르게 발려요.",
    tags: ["틴트", "밑작업", "요령"],
    points: 8,
    type: "action",
  },
  {
    id: "lip-homemade-gloss",
    category: "lip",
    title: "바세린으로 립글로스 만들기",
    materials: ["바세린 1티스푼", "쓰던 립스틱 조금", "작은 통"],
    steps: [
      "립스틱 끝을 조금 잘라 통에 넣어 주세요.",
      "바세린을 넣고 따뜻한 물에 통을 담가 살살 녹여 주세요.",
      "잘 섞은 뒤 굳혀 주세요.",
    ],
    effect: "내 입술색에 맞는 촉촉한 립글로스를 만들 수 있어요.",
    caution: "직접 불에 올려 녹이지 마세요. 따뜻한 물에 중탕하는 정도가 안전합니다.",
    tags: ["만들기", "그시절", "립글로스"],
    points: 10,
    type: "action",
  },
  {
    id: "lip-water",
    category: "lip",
    title: "물 마셔서 입술 지키기",
    steps: [
      "입술이 자주 트면 하루 물 양부터 늘려 주세요.",
      "난방을 켠 방에는 젖은 수건을 걸어 두세요.",
    ],
    effect: "속부터 마르지 않아 입술이 덜 갈라져요.",
    tags: ["수분", "겨울", "기본"],
    points: 8,
    type: "action",
  },
  {
    id: "teeth-brush-way",
    category: "lip",
    title: "칫솔질 3분 지키기",
    materials: ["칫솔", "치약"],
    steps: [
      "치약은 완두콩 크기만 짜 주세요.",
      "칫솔을 잇몸 쪽에 45도로 대고 쓸어내려 주세요.",
      "앞니 안쪽과 어금니 씹는 면까지 3분 동안 닦아 주세요.",
      "혀도 안쪽에서 앞으로 두세 번 쓸어 주세요.",
    ],
    effect: "치아 표면이 매끄러워지고 입냄새가 줄어들어요.",
    tags: ["기본", "3분", "매일"],
    points: 10,
    type: "action",
  },
  {
    id: "teeth-after-acid",
    category: "lip",
    title: "신 음식 먹고 바로 양치하지 않기",
    steps: [
      "탄산음료나 신 과일을 먹은 뒤에는 물로 입을 헹궈 주세요.",
      "30분 정도 기다렸다가 양치해 주세요.",
    ],
    effect: "약해진 치아 표면이 깎이지 않아 이가 오래 튼튼해요.",
    tags: ["치아보호", "30분", "습관"],
    points: 8,
    type: "action",
  },
  {
    id: "teeth-color-care",
    category: "lip",
    title: "치아 착색 줄이기",
    steps: [
      "커피·홍차·콜라를 마신 뒤에는 물로 입을 헹궈 주세요.",
      "빨대를 쓰면 앞니에 덜 닿아요.",
      "칫솔은 3개월에 한 번 바꿔 주세요.",
    ],
    effect: "치아가 누레지는 속도를 늦출 수 있어요.",
    caution: "베이킹소다나 소금으로 이를 문지르면 치아 표면이 마모될 수 있어요. 자주 하지 마세요.",
    tags: ["착색", "커피", "습관"],
    points: 10,
    type: "action",
  },
  {
    id: "teeth-floss",
    category: "lip",
    title: "치실 쓰기",
    materials: ["치실"],
    steps: [
      "자기 전 한 번은 치실을 써 주세요.",
      "치아 사이에 넣고 잇몸 쪽으로 살짝 눌러 옆면을 훑어 주세요.",
      "한 칸마다 실을 조금씩 옮겨 새 부분을 써 주세요.",
    ],
    effect: "칫솔이 닿지 않던 자리가 깨끗해져 입냄새가 줄어요.",
    tags: ["치실", "자기전", "기본"],
    points: 10,
    type: "action",
  },
  {
    id: "lip-smile-line",
    category: "lip",
    title: "입꼬리 올리는 연습",
    steps: [
      "거울을 보고 입꼬리만 살짝 올려 10초 유지해 주세요.",
      "'이' 소리를 내는 입 모양으로 10초 더 유지해 주세요.",
      "아침저녁으로 다섯 번씩 해 주세요.",
    ],
    effect: "표정이 부드러워지고 인상이 밝아 보여요.",
    tags: ["표정", "10초", "거울앞"],
    points: 8,
    type: "action",
  },
];
