import type { HunnyeoTip } from "./types";

// ── 제4장 붓기빼기 ─────────────────────────────────────────────────────────
export const SWELLING_TIPS: HunnyeoTip[] = [
  {
    id: "swell-cold-spoon",
    category: "swelling",
    title: "찬 숟가락 눈두덩 찜질",
    materials: ["숟가락 2개"],
    steps: [
      "숟가락 두 개를 냉장고에 넣어 두세요.",
      "아침에 꺼내 등이 눈두덩에 닿도록 올려 주세요.",
      "1분 정도 대고 있다가 미지근해지면 떼어 주세요.",
    ],
    effect: "부어 있던 눈두덩이 금세 가라앉아요.",
    tags: ["아침", "눈", "1분"],
    points: 8,
    type: "action",
  },
  {
    id: "swell-teabag",
    category: "swelling",
    title: "찬 녹차 티백 올리기",
    materials: ["사용한 녹차 티백 2개"],
    steps: [
      "우린 티백을 냉장고에 넣어 차갑게 식혀 주세요.",
      "물기를 살짝 짜고 눈 위에 올려 주세요.",
      "5분 뒤 떼어내고 물로 가볍게 헹궈 주세요.",
    ],
    effect: "눈가가 시원하게 진정되고 부기가 줄어들어요.",
    tags: ["눈", "5분", "재활용"],
    points: 8,
    type: "action",
  },
  {
    id: "swell-face-massage",
    category: "swelling",
    title: "얼굴 림프 쓸어내리기",
    materials: ["로션 또는 오일 약간"],
    steps: [
      "귀 뒤 움푹 들어간 곳을 손가락으로 가볍게 눌러 주세요.",
      "턱선을 따라 귀 쪽으로 손바닥 전체를 써서 쓸어 주세요.",
      "귀 아래에서 쇄골 방향으로 목을 따라 내려 주세요.",
      "한쪽에 열 번씩 반복해 주세요.",
    ],
    effect: "얼굴선이 정돈되고 아침 부기가 빠르게 가라앉아요.",
    tags: ["마사지", "턱선", "아침"],
    points: 12,
    type: "action",
  },
  {
    id: "swell-pillow-height",
    category: "swelling",
    title: "베개 높이 조절하기",
    materials: ["베개 또는 수건"],
    steps: [
      "머리가 심장보다 살짝 높아지도록 베개를 맞춰 주세요.",
      "너무 낮으면 수건을 접어 아래에 받쳐 주세요.",
      "엎드려 자는 습관이 있다면 옆으로 눕는 자세로 바꿔 주세요.",
    ],
    effect: "아침에 얼굴이 붓는 정도가 눈에 띄게 줄어들어요.",
    tags: ["수면", "아침부기", "자세"],
    points: 10,
    type: "action",
  },
  {
    id: "swell-potassium",
    category: "swelling",
    title: "칼륨이 많은 음식 챙기기",
    materials: ["바나나", "토마토", "미역", "아스파라거스"],
    steps: [
      "짠 음식을 먹은 다음 날에 챙겨 드세요.",
      "아침 식사에 바나나 한 개나 토마토 한 개를 더해 주세요.",
      "국은 건더기 위주로 먹고 국물은 남겨 주세요.",
    ],
    effect: "몸에 남은 나트륨이 빠져나가 부기가 덜해져요.",
    tags: ["칼륨", "식습관", "다음날"],
    points: 10,
    type: "action",
  },
  {
    id: "swell-leg-up",
    category: "swelling",
    title: "벽에 다리 올리기",
    steps: [
      "벽 가까이 누워 엉덩이를 벽에 붙여 주세요.",
      "다리를 벽에 대고 곧게 올려 주세요.",
      "10분 정도 편하게 호흡하며 유지해 주세요.",
      "내릴 때는 무릎을 굽혀 천천히 옆으로 내려 주세요.",
    ],
    effect: "종아리가 가벼워지고 다리 부기가 빠져요.",
    tags: ["다리", "10분", "자기전"],
    points: 12,
    type: "action",
  },
  {
    id: "swell-calf-stretch",
    category: "swelling",
    title: "종아리 늘리기 스트레칭",
    steps: [
      "벽을 짚고 한쪽 다리를 뒤로 크게 뻗어 주세요.",
      "뒷발 뒤꿈치를 바닥에 붙인 채 앞무릎을 굽혀 주세요.",
      "종아리가 당기는 느낌으로 30초 유지해 주세요.",
      "반대쪽도 같은 방법으로 해 주세요.",
    ],
    effect: "뭉친 종아리가 풀리고 다리 선이 매끈해 보여요.",
    tags: ["종아리", "30초", "매일"],
    points: 12,
    type: "action",
  },
  {
    id: "swell-calf-massage",
    category: "swelling",
    title: "종아리 아래에서 위로 주무르기",
    materials: ["로션 또는 오일"],
    steps: [
      "로션을 발라 미끄럽게 해 주세요.",
      "발목에서 무릎 방향으로만 쓸어 올려 주세요.",
      "뭉친 곳은 엄지로 지그시 눌렀다 떼어 주세요.",
      "한쪽에 3분씩 해 주세요.",
    ],
    effect: "다리가 가벼워지고 잘 때 저리는 느낌이 줄어들어요.",
    caution: "위에서 아래로 문지르면 순환에 도움이 되지 않아요. 방향을 지켜 주세요.",
    tags: ["마사지", "3분", "자기전"],
    points: 10,
    type: "action",
  },
  {
    id: "swell-ankle-circle",
    category: "swelling",
    title: "발목 돌리기",
    steps: [
      "앉은 자세에서 한쪽 다리를 살짝 들어 주세요.",
      "발목을 크게 안쪽으로 스무 번 돌려 주세요.",
      "바깥쪽으로도 스무 번 돌려 주세요.",
    ],
    effect: "오래 앉아 있어 무거워진 다리가 한결 가벼워져요.",
    tags: ["발목", "책상에서", "간단"],
    points: 8,
    type: "action",
  },
  {
    id: "swell-warm-bath",
    category: "swelling",
    title: "따뜻한 족욕",
    materials: ["대야", "따뜻한 물"],
    steps: [
      "복사뼈가 잠길 만큼 따뜻한 물을 받아 주세요.",
      "15분 정도 발을 담가 주세요.",
      "끝나면 찬물로 20초 정도 헹궈 마무리해 주세요.",
    ],
    effect: "발과 다리의 순환이 좋아지고 잠이 잘 와요.",
    tags: ["족욕", "15분", "자기전"],
    points: 10,
    type: "action",
  },
  {
    id: "swell-no-cross",
    category: "swelling",
    title: "다리 꼬지 않기",
    steps: [
      "앉을 때 두 발을 모두 바닥에 붙여 주세요.",
      "무릎과 발끝이 같은 방향을 보게 해 주세요.",
      "한 시간에 한 번은 일어나 걸어 주세요.",
    ],
    effect: "골반이 틀어지지 않고 다리 붓기도 덜해져요.",
    tags: ["자세", "골반", "습관"],
    points: 10,
    type: "action",
  },
  {
    id: "swell-night-water",
    category: "swelling",
    title: "자기 전 물 줄이기",
    steps: [
      "잠들기 한 시간 전부터는 물을 많이 마시지 말아 주세요.",
      "대신 낮 동안 나눠서 충분히 마셔 주세요.",
      "짠 야식을 먹었다면 자기 전 스트레칭을 해 주세요.",
    ],
    effect: "아침에 얼굴과 손이 붓는 일이 줄어들어요.",
    tags: ["수분", "아침부기", "습관"],
    points: 8,
    type: "action",
  },
];
