import type { HunnyeoTip } from "./types";

// ── 제11장 몸매·자세 ───────────────────────────────────────────────────────
export const BODY_TIPS: HunnyeoTip[] = [
  {
    id: "body-wall-posture",
    category: "body",
    title: "벽에 붙어 서기",
    steps: [
      "벽에 뒤통수·등·엉덩이·종아리를 붙이고 서 주세요.",
      "허리와 벽 사이에 손바닥 하나가 겨우 들어갈 정도로 맞춰 주세요.",
      "그 자세로 1분 유지해 주세요.",
      "하루 세 번 해 주세요.",
    ],
    effect: "굽은 등이 펴지고 서 있는 자세가 반듯해져요.",
    tags: ["자세교정", "1분", "매일"],
    points: 12,
    type: "action",
  },
  {
    id: "body-turtle-neck",
    category: "body",
    title: "거북목 당기기",
    steps: [
      "턱을 뒤로 당겨 이중턱을 만든다는 느낌으로 밀어 주세요.",
      "5초 유지하고 힘을 빼 주세요.",
      "10번씩 하루 세 번 해 주세요.",
    ],
    effect: "목이 앞으로 나온 자세가 교정되고 어깨 결림이 줄어요.",
    tags: ["거북목", "5초", "책상에서"],
    points: 12,
    type: "action",
  },
  {
    id: "body-shoulder-open",
    category: "body",
    title: "말린 어깨 펴기",
    steps: [
      "등 뒤에서 두 손을 깍지 껴 주세요.",
      "가슴을 내밀며 팔을 아래로 쭉 내려 주세요.",
      "20초 유지하고 세 번 반복해 주세요.",
    ],
    effect: "굽은 어깨가 펴져 상체 라인이 살아나요.",
    tags: ["라운드숄더", "20초", "간단"],
    points: 10,
    type: "action",
  },
  {
    id: "body-collarbone",
    category: "body",
    title: "쇄골 라인 마사지",
    materials: ["로션"],
    steps: [
      "쇄골 위쪽 홈을 손가락으로 가볍게 눌러 주세요.",
      "어깨 쪽에서 목 아래 가운데 방향으로 쓸어 주세요.",
      "한쪽에 열 번씩 해 주세요.",
    ],
    effect: "쇄골 라인이 또렷해 보이고 목이 길어 보여요.",
    tags: ["쇄골", "마사지", "간단"],
    points: 8,
    type: "action",
  },
  {
    id: "body-plank",
    category: "body",
    title: "플랭크 30초",
    steps: [
      "팔꿈치를 바닥에 대고 몸을 일직선으로 만들어 주세요.",
      "엉덩이가 솟거나 처지지 않게 배에 힘을 주세요.",
      "30초 버티고 30초 쉬기를 세 번 해 주세요.",
    ],
    effect: "허리와 배에 힘이 붙어 자세가 안정돼요.",
    caution: "허리가 아프면 바로 멈추고 무릎을 대고 하는 자세로 바꿔 주세요.",
    tags: ["코어", "30초", "집운동"],
    points: 12,
    type: "action",
  },
  {
    id: "body-hip-bridge",
    category: "body",
    title: "엉덩이 들어 올리기",
    steps: [
      "누워서 무릎을 세우고 발을 골반 너비로 벌려 주세요.",
      "엉덩이에 힘을 주며 몸을 들어 올려 주세요.",
      "위에서 2초 멈췄다가 천천히 내려 주세요.",
      "15번씩 세 세트 해 주세요.",
    ],
    effect: "엉덩이에 힘이 붙어 뒤태와 허리 선이 살아나요.",
    tags: ["힙업", "15번", "누워서"],
    points: 12,
    type: "action",
  },
  {
    id: "body-pelvis-stretch",
    category: "body",
    title: "골반 좌우 균형 잡기",
    steps: [
      "가방을 늘 같은 쪽으로 메지 않도록 바꿔 주세요.",
      "서 있을 때 짝다리를 짚지 말아 주세요.",
      "누워서 무릎을 모아 좌우로 천천히 눕히는 동작을 열 번 해 주세요.",
    ],
    effect: "골반이 틀어지지 않아 옷 맵시가 반듯해져요.",
    tags: ["골반", "습관", "스트레칭"],
    points: 10,
    type: "action",
  },
  {
    id: "body-armpit-care",
    category: "body",
    title: "겨드랑이 색 관리",
    steps: [
      "면도날로 매일 밀지 말고 주기를 늘려 주세요.",
      "제모 후에는 진정 로션을 발라 주세요.",
      "꽉 끼는 옷을 피해 마찰을 줄여 주세요.",
    ],
    effect: "자극으로 짙어지던 색이 서서히 옅어져요.",
    caution: "레몬즙이나 표백 성분을 바르면 자극으로 오히려 색이 짙어질 수 있어요.",
    tags: ["겨드랑이", "제모", "자극줄이기"],
    points: 10,
    type: "action",
  },
  {
    id: "body-back-care",
    category: "body",
    title: "등 트러블 관리",
    steps: [
      "머리를 감고 헹군 다음에 몸을 씻어 주세요.",
      "샴푸와 린스가 등에 남지 않게 마지막에 등을 헹궈 주세요.",
      "땀에 젖은 옷은 바로 갈아입어 주세요.",
    ],
    effect: "등에 올라오던 오돌토돌한 것이 줄어들어요.",
    tags: ["등", "샤워순서", "습관"],
    points: 10,
    type: "action",
  },
  {
    id: "body-arm-line",
    category: "body",
    title: "팔뚝 뒤쪽 힘주기",
    materials: ["물병 2개"],
    steps: [
      "물병을 양손에 들고 팔을 머리 위로 뻗어 주세요.",
      "팔꿈치만 굽혀 물병을 뒤로 내렸다 올려 주세요.",
      "15번씩 세 세트 해 주세요.",
    ],
    effect: "팔 뒤쪽이 단단해져 반팔 입을 때 라인이 정리돼요.",
    tags: ["팔뚝", "물병운동", "15번"],
    points: 10,
    type: "action",
  },
  {
    id: "body-walk-line",
    category: "body",
    title: "일자로 걷기 연습",
    steps: [
      "바닥의 선 하나를 정해 그 위를 걷는다고 생각해 주세요.",
      "발끝이 바깥이나 안으로 벌어지지 않게 앞을 보게 해 주세요.",
      "어깨는 펴고 시선은 정면보다 조금 위를 봐 주세요.",
    ],
    effect: "걸음걸이가 반듯해지고 다리 모양이 예뻐 보여요.",
    tags: ["걸음걸이", "자세", "매일"],
    points: 10,
    type: "action",
  },
  {
    id: "body-stretch-morning",
    category: "body",
    title: "아침 기지개 3분",
    steps: [
      "누운 채로 팔과 다리를 위아래로 길게 뻗어 주세요.",
      "무릎을 안고 등을 둥글게 말아 좌우로 흔들어 주세요.",
      "앉아서 목을 좌우로 천천히 기울여 주세요.",
    ],
    effect: "몸이 개운해지고 하루 종일 자세가 덜 무너져요.",
    tags: ["아침", "3분", "스트레칭"],
    points: 8,
    type: "action",
  },
];
