import type { HunnyeoTip } from "./types";

// ── 제12장 생활습관 ────────────────────────────────────────────────────────
export const LIFE_TIPS: HunnyeoTip[] = [
  {
    id: "life-sleep-time",
    category: "life",
    title: "열 시에서 두 시 사이에 자기",
    steps: [
      "밤 열 시에서 새벽 두 시 사이에는 잠들어 있게 해 주세요.",
      "자기 한 시간 전에는 방 불을 어둡게 해 주세요.",
      "주말에도 일어나는 시간을 비슷하게 맞춰 주세요.",
    ],
    effect: "피부와 머리카락이 회복되고 다음 날 얼굴빛이 달라져요.",
    tags: ["수면", "피부회복", "기본중의기본"],
    points: 12,
    type: "action",
  },
  {
    id: "life-humidifier",
    category: "life",
    title: "젖은 수건 걸어 두기",
    materials: ["수건 1~2장"],
    steps: [
      "잠들기 전 젖은 수건을 짜서 방에 걸어 주세요.",
      "난방을 켠 날에는 두 장 걸어 주세요.",
    ],
    effect: "아침에 목이 마르지 않고 피부 당김도 줄어들어요.",
    tags: ["습도", "겨울", "간단"],
    points: 8,
    type: "action",
  },
  {
    id: "life-perfume",
    category: "life",
    title: "향수 은은하게 뿌리기",
    materials: ["향수"],
    steps: [
      "옷을 입기 전 몸에서 20cm 떨어뜨려 공중에 뿌리고 그 아래를 지나가 주세요.",
      "손목·귀 뒤·머리끝 중 한 곳만 골라 주세요.",
      "손목끼리 비비지 말아 주세요.",
    ],
    effect: "가까이 왔을 때만 은은하게 느껴지는 향이 만들어져요.",
    tags: ["향수", "20cm", "은은하게"],
    points: 8,
    type: "action",
  },
  {
    id: "life-hair-scent",
    category: "life",
    title: "머리에서 좋은 냄새 나게 하기",
    materials: ["빗", "향수"],
    steps: [
      "빗에 향수를 한 번 뿌려 주세요.",
      "3초 기다렸다가 머리를 빗어 주세요.",
    ],
    effect: "머리카락이 흔들릴 때마다 은은한 향이 남아요.",
    caution: "머리카락에 직접 뿌리면 알코올 때문에 건조해질 수 있어요.",
    tags: ["머리향", "빗", "요령"],
    points: 8,
    type: "action",
  },
  {
    id: "life-closet-scent",
    category: "life",
    title: "옷장에 향 넣어 두기",
    materials: ["섬유유연제 묻힌 천 조각 또는 비누 한 개"],
    steps: [
      "쓰지 않는 비누를 포장한 채로 옷장에 넣어 주세요.",
      "서랍마다 하나씩 넣어 주세요.",
      "한 달에 한 번 위치를 바꿔 주세요.",
    ],
    effect: "꺼내 입는 옷에서 은은한 향이 나요.",
    tags: ["옷장", "비누", "한달"],
    points: 6,
    type: "action",
  },
  {
    id: "life-morning-light",
    category: "life",
    title: "아침에 커튼 걷기",
    steps: [
      "일어나면 바로 커튼을 걷고 창가에 서 주세요.",
      "5분 정도 바깥 빛을 봐 주세요.",
    ],
    effect: "잠이 빨리 깨고 밤에 잠드는 시간도 앞당겨져요.",
    tags: ["아침", "5분", "수면리듬"],
    points: 8,
    type: "action",
  },
  {
    id: "life-phone-off",
    category: "life",
    title: "자기 전 화면 끄기",
    steps: [
      "잠들기 30분 전에 휴대전화를 손이 닿지 않는 곳에 두세요.",
      "대신 책이나 라디오를 켜 주세요.",
    ],
    effect: "잠들기까지 걸리는 시간이 짧아지고 다음 날 눈이 덜 붓어요.",
    tags: ["수면", "30분", "습관"],
    points: 10,
    type: "action",
  },
  {
    id: "life-towel-change",
    category: "life",
    title: "세수 수건 따로 쓰기",
    materials: ["작은 수건 여러 장"],
    steps: [
      "얼굴 전용 수건을 따로 정해 주세요.",
      "이틀에 한 번은 새 수건으로 바꿔 주세요.",
      "얼굴은 문지르지 말고 눌러서 닦아 주세요.",
    ],
    effect: "트러블이 줄고 세안 후 자극이 덜해요.",
    tags: ["수건", "트러블예방", "습관"],
    points: 8,
    type: "action",
  },
  {
    id: "life-brush-clean",
    category: "life",
    title: "화장 도구 씻기",
    materials: ["중성 세제 또는 비누", "미온수"],
    steps: [
      "퍼프와 브러시를 미온수에 담가 주세요.",
      "세제를 조금 풀어 조물조물 빨아 주세요.",
      "충분히 헹구고 눕혀서 그늘에 말려 주세요.",
      "퍼프는 주 1회, 브러시는 2주에 한 번 씻어 주세요.",
    ],
    effect: "화장이 잘 먹고 트러블이 눈에 띄게 줄어들어요.",
    tags: ["퍼프", "브러시", "주 1회"],
    points: 10,
    type: "action",
  },
  {
    id: "life-bag-light",
    category: "life",
    title: "가방 가볍게 하고 양쪽 번갈아 메기",
    steps: [
      "가방에서 오늘 쓰지 않을 물건을 빼 주세요.",
      "한쪽 어깨로만 메지 말고 번갈아 메 주세요.",
      "무거운 날은 배낭이나 크로스백을 써 주세요.",
    ],
    effect: "어깨가 한쪽으로 기울지 않아 자세가 반듯해져요.",
    tags: ["가방", "어깨", "습관"],
    points: 8,
    type: "action",
  },
  {
    id: "life-water-bottle",
    category: "life",
    title: "물병 들고 다니기",
    materials: ["텀블러 또는 물병"],
    steps: [
      "아침에 물병을 채워 가방에 넣어 주세요.",
      "점심 전까지 절반을 비우는 것을 목표로 해 주세요.",
      "다 마시면 한 번 더 채워 주세요.",
    ],
    effect: "하루 물 양이 자연스럽게 늘어 피부와 컨디션이 좋아져요.",
    tags: ["수분", "텀블러", "매일"],
    points: 8,
    type: "action",
  },
  {
    id: "life-sunscreen-habit",
    category: "life",
    title: "현관에 자외선 차단제 두기",
    materials: ["자외선 차단제"],
    steps: [
      "신발장 위에 자외선 차단제를 놓아 주세요.",
      "신발을 신기 전에 바르는 것으로 순서를 정해 주세요.",
      "흐린 날에도 똑같이 발라 주세요.",
    ],
    effect: "잊지 않고 매일 바르게 되어 잡티가 늦게 생겨요.",
    tags: ["자외선", "현관", "매일"],
    points: 10,
    type: "action",
  },
  {
    id: "life-diary",
    category: "life",
    title: "다이어리 꾸미기",
    materials: ["다이어리", "스티커", "색펜"],
    steps: [
      "하루에 한 줄만 적는다고 정해 주세요.",
      "좋았던 일 하나와 내일 할 일 하나만 써 주세요.",
      "스티커는 다 쓴 날에만 붙여 주세요.",
    ],
    effect: "기분이 정리되고 그 시절 다이어리 감성도 되살아나요.",
    tags: ["다이어리", "한줄", "그시절"],
    points: 6,
    type: "action",
  },
  {
    id: "life-mirror-check",
    category: "life",
    title: "나가기 전 전신거울 3초 확인",
    materials: ["전신거울"],
    steps: [
      "현관에서 전신거울을 3초만 봐 주세요.",
      "어깨가 펴졌는지, 옷매무새가 맞는지 확인해 주세요.",
    ],
    effect: "작은 흐트러짐을 잡아 하루 인상이 달라져요.",
    tags: ["거울", "3초", "습관"],
    points: 6,
    type: "action",
  },
];
